# Generated by Django 4.1.6 on 2023-02-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FIRSTAPPLICATION', '0003_employee_gender_person_delete_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='gender_field',
            field=models.CharField(max_length=1),
        ),
    ]
