# Generated by Django 4.1.6 on 2023-02-02 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FIRSTAPPLICATION', '0004_alter_gender_gender_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.CharField(max_length=20)),
                ('salary', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gender1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_field', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Person1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('contact', models.IntegerField()),
                ('birthdate', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='gender',
            name='person',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='gender1',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FIRSTAPPLICATION.person1'),
        ),
        migrations.AddField(
            model_name='employee1',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FIRSTAPPLICATION.person1'),
        ),
    ]
